figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs/run_003/figures/eval_epoch_0120/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs/run_003/figures/eval_epoch_0120/figC_dynamics_2x2.png"
observations_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/data/dataset_c45390420f42ffabe38b95cf1dab85d2c77799c2.hdf5"
device = "GPU:1"
metrics_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs/run_003/metrics/epoch_0120_langevin_metrics.txt"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs/run_003/model/score_model.bson"

[metrics]
avg_mode_js_clipped = 0.004169630079104736
global_kl_from_run_langevin = 0.0026949125244138963
avg_mode_kl_clipped = 0.01699101878809588
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.02830914154972078
stein_sample_stride = 34.0
