metrics_txt_path = ""
eval_config_path = ""
epoch = 30

[metrics]
kl_low_q = 0.001
avg_mode_kl_raw = 0.12338570154188735
score_pred_mse = 0.842454236172085
avg_mode_l1_raw = 0.0058728397286954715
avg_channel_std_abs_error = 0.5539859533309937
avg_mode_kl_clipped = 0.11992795759997
avg_mode_l1_clipped = 0.0058101430568949985
avg_x_channel_kl_raw = 0.16254182825515187
score_pred_corr = 0.3971660329295541
avg_channel_std_rel_error = 0.5332330276368462
avg_mode_js_clipped = 0.03449756746277292
max_mode_kl_raw = 0.19663295816985632
avg_y_channels_kl_raw = 0.11947008887056094
kl_high_q = 0.999
avg_x_channel_kl_clipped = 0.15823845468207048
global_kl_from_run_langevin = 0.10824511179415236
avg_mode_js_raw = 0.03564626590799579
avg_y_channels_kl_clipped = 0.11609690789175997
target_avg_mode_kl = 0.05
avg_channel_mean_abs_error = 0.23524880409240723
max_mode_kl_clipped = 0.19322198716014427
