smape_gaussian_vs_numerical = 0.4991739729434434
global_kl = 0.003816910064876186
epoch = 40
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/model/checkpoints/epoch_0040.bson"
avg_mode_kl_clipped = 0.007083252527917219
smape_unet_vs_numerical = 0.3844754634734096

[langevin_metrics]
avg_mode_js_clipped = 0.0017777145325324599
global_kl_from_run_langevin = 0.003816910064876186
avg_mode_kl_clipped = 0.007083252527917219
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.013026113610582389
stein_sample_stride = 167.0

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/figures/eval_epoch_0040/responses/run_001/responses_5x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/figures/eval_epoch_0040/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/figures/eval_epoch_0040/figD_responses_5x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/figures/eval_epoch_0040/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/figures/eval_epoch_0040/figC_dynamics_2x2.png"
