global_kl = 0.005311115579074004
epoch = 40
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_030/model/checkpoints/epoch_0040.bson"
avg_mode_kl_clipped = 0.023600517043837126
smape_unet_vs_numerical = 0.5546231322142675

[langevin_metrics]
avg_mode_js_clipped = 0.005737994458364469
global_kl_from_run_langevin = 0.005311115579074004
avg_mode_kl_clipped = 0.023600517043837126
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.03782048378707805
stein_sample_stride = 167.0

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_030/figures/eval_epoch_0040/responses/run_001/responses_5x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_030/figures/eval_epoch_0040/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_030/figures/eval_epoch_0040/figD_responses_5x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_030/figures/eval_epoch_0040/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_030/figures/eval_epoch_0040/figC_dynamics_2x2.png"
