figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0002/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0002/figC_dynamics_2x2.png"
observations_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/l96_x_train_smoke.hdf5"
device = "GPU:1"
metrics_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/metrics/epoch_0002_langevin_metrics.txt"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/model/checkpoints/epoch_0002.bson"

[metrics]
avg_mode_js_clipped = 0.2233573851349891
global_kl_from_run_langevin = 0.1196789577296175
avg_mode_kl_clipped = 0.7515997960626137
langevin_ensembles = 32.0
target_avg_mode_kl = 0.05
langevin_resolution = 8.0
langevin_nsteps = 2500.0
max_mode_kl_clipped = 0.9696162471123954
