global_kl = 0.031451076748650074
epoch = 2
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_010/model/checkpoints/epoch_0002.bson"
avg_mode_kl_clipped = 0.17269323840431913
smape_unet_vs_numerical = nan

[langevin_metrics]
avg_mode_js_clipped = 0.02370760890600471
global_kl_from_run_langevin = 0.031451076748650074
avg_mode_kl_clipped = 0.17269323840431913
langevin_ensembles = 32.0
target_avg_mode_kl = 0.05
langevin_resolution = 8.0
langevin_nsteps = 2500.0
max_mode_kl_clipped = 0.26716093205054425
stein_sample_stride = 34.0

[responses]
summary = ""
run_dir = ""

[figures]
figD = ""
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_010/figures/eval_epoch_0002/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_010/figures/eval_epoch_0002/figC_dynamics_2x2.png"
