[run]
run_id_padding = 3
runs_root = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs"

[evaluation]
evaluate_final_model = true
response_apply_correction = true
run_langevin = true
evaluate_every_checkpoint = false
run_responses = true
response_kind = "heaviside"

[paths]
responses_params = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/configs/05_response_hutch_probe20/parameters_responses.toml"
train_params = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/configs/05_response_hutch_probe20/parameters_train.toml"
langevin_params = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/parameters_langevin.toml"

[targets]
target_avg_mode_kl = 0.01

[resources]
responses_threads = "auto"
queue_poll_seconds = 1.0
langevin_device = "GPU:1"
checkpoint_poll_seconds = 2.0
train_device = "GPU:0"
responses_score_device = "GPU:1"
