metrics_txt_path = ""
eval_config_path = ""
epoch = 40

[metrics]
kl_low_q = 0.001
avg_mode_kl_raw = 0.12194440111274778
score_pred_mse = 0.8219425803702626
avg_mode_l1_raw = 0.005809224229811502
avg_channel_std_abs_error = 0.5448086261749268
avg_mode_kl_clipped = 0.11870039882912971
avg_mode_l1_clipped = 0.005747419536073028
avg_x_channel_kl_raw = 0.18970496335970266
score_pred_corr = 0.42219626616176303
avg_channel_std_rel_error = 0.52488326057251
avg_mode_js_clipped = 0.03430065849474973
max_mode_kl_raw = 0.31252487119520966
avg_y_channels_kl_raw = 0.1151683448880523
kl_high_q = 0.999
avg_x_channel_kl_clipped = 0.1862074359538617
global_kl_from_run_langevin = 0.10534051224808198
avg_mode_js_raw = 0.03532549044937367
avg_y_channels_kl_clipped = 0.11194969511665652
target_avg_mode_kl = 0.05
avg_channel_mean_abs_error = 0.2779656946659088
max_mode_kl_clipped = 0.3105250702622334
