global_kl = 0.006524123126121955
epoch = 50
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_028/model/checkpoints/epoch_0050.bson"
avg_mode_kl_clipped = 0.010021954940112118
smape_unet_vs_numerical = 0.4961279977101287

[langevin_metrics]
avg_mode_js_clipped = 0.002544549738223955
global_kl_from_run_langevin = 0.006524123126121955
avg_mode_kl_clipped = 0.010021954940112118
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.013108080590440342
stein_sample_stride = 34.0

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_028/figures/eval_epoch_0050/responses/run_001/responses_5x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_028/figures/eval_epoch_0050/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_028/figures/eval_epoch_0050/figD_responses_5x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_028/figures/eval_epoch_0050/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_028/figures/eval_epoch_0050/figC_dynamics_2x2.png"
