global_kl = 0.005048586877933269
epoch = 180
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/model/checkpoints/epoch_0180.bson"
avg_mode_kl_clipped = 0.009382892893334273
smape_unet_vs_numerical = 0.44674418256421333

[langevin_metrics]
avg_mode_js_clipped = 0.00235513530406121
global_kl_from_run_langevin = 0.005048586877933269
avg_mode_kl_clipped = 0.009382892893334273
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.014693984212259573
stein_sample_stride = 34.0

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0180/responses/run_001/responses_5x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0180/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0180/figD_responses_5x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0180/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0180/figC_dynamics_2x2.png"
