global_kl = 0.006886773466762814
epoch = 60
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/model/checkpoints/epoch_0060.bson"
avg_mode_kl_clipped = 0.009083360325956863
smape_unet_vs_numerical = 0.44862645465432516

[langevin_metrics]
avg_mode_js_clipped = 0.002287804124775748
global_kl_from_run_langevin = 0.006886773466762814
avg_mode_kl_clipped = 0.009083360325956863
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.012410128815695906
stein_sample_stride = 34.0

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0060/responses/run_001/responses_5x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0060/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0060/figD_responses_5x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0060/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_027/figures/eval_epoch_0060/figC_dynamics_2x2.png"
