cache_regenerated = true
output_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001"
response_kind = "heaviside"
run_id = "run_001"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/model/checkpoints/epoch_0060.bson"
apply_score_correction = true
h_used = [0.05, 0.02, 0.01, 0.00125, 0.01]
cache_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/cache/responses/baseline_d4e98787404bf36d9034228bbd7fbab88248572b.hdf5"

[numerical_diag]
valid_fraction = [1.0, 1.0, 1.0, 1.0, 1.0]
valid_counts = [2048, 2048, 2048, 2048, 2048]
h_attempts = [1, 1, 1, 3, 1]

[figures]
raw = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001/responses_6x5_selected_methods_raw.png"
main = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001/responses_6x5_selected_methods.png"
corrected = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001/responses_6x5_selected_methods_corrected.png"

[outputs]
responses_csv = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001/responses_6x5_selected_methods.csv"
responses_hdf5 = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001/responses_6x5_selected_methods.hdf5"
parameters_used = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001/parameters_used.toml"

[rmse.numerics_vs_unet_corrected]
overall = 154669.42027625054

    [rmse.numerics_vs_unet_corrected.per_param]
    sigma = 227.57752453002544
    alpha2 = 24758.02488272601
    alpha1 = 1990.547973396434
    alpha3 = 344958.17691588204
    alpha0 = 173.64610622943965

[rmse.numerics_vs_gaussian]
overall = 169567.85945411253

    [rmse.numerics_vs_gaussian.per_param]
    sigma = 116.00840832609268
    alpha2 = 26257.291562965314
    alpha1 = 2364.5599715681537
    alpha3 = 378247.54617366905
    alpha0 = 196.59810400243688

[rmse.numerics_vs_unet_raw]
overall = 116169.4033379096

    [rmse.numerics_vs_unet_raw.per_param]
    sigma = 112.30906505709865
    alpha2 = 14563.25493457099
    alpha1 = 1695.0462857640987
    alpha3 = 259348.5435551476
    alpha0 = 100.6266751878384

[closure_parameters_used]
sigma = 0.22408113973792695
alpha2 = 0.0004226502150517753
alpha1 = 1.116425972669803
alpha3 = -0.003108940311701304
beta_tail = -2.0
alpha0 = 0.7610633766768744
F = 20.0
