rmse_unet_vs_numerical = 154669.42027625054
global_kl = 0.07792338925660253
epoch = 60
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/model/checkpoints/epoch_0060.bson"
avg_mode_kl_clipped = 0.09897821737500564

[langevin_metrics]
avg_mode_js_clipped = 0.01658509694402471
global_kl_from_run_langevin = 0.07792338925660253
avg_mode_kl_clipped = 0.09897821737500564
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.14631084777357686

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001/responses_6x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/figD_responses_6x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_005/figures/eval_epoch_0060/figC_dynamics_2x2.png"
