figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/figures/eval_epoch_0010/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/figures/eval_epoch_0010/figC_dynamics_2x2.png"
observations_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/data/l96_arnold_datasets.hdf5"
device = "GPU:1"
metrics_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/metrics/epoch_0010_langevin_metrics.txt"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_037/model/checkpoints/epoch_0010.bson"

[metrics]
avg_mode_js_clipped = 0.001993963485324605
global_kl_from_run_langevin = 0.005027597524611329
avg_mode_kl_clipped = 0.007781884014646714
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.01693142077141487
stein_sample_stride = 167.0
