[l96]
J = 10
c = 10.0
save_every = 20
delta_t_obs = 0.1
process_noise_sigma = 0.03
b = 10.0
dt = 0.005
K = 36
h = 1.0
F = 10.0

[score_correction.unet]
pre_identity_rmse = 5.4929969875053235
post_identity_rmse_direct = 3.803278919337359e-8
ridge = 1.0e-8
post_identity_rmse_pinv = 3.8032797551135075e-8
solver = "direct_solve"
cond_regularized = 2075.0421382597115
post_identity_rmse = 3.803278919337359e-8

[score_correction.gaussian]
pre_identity_rmse = 6.669445091085705e-6
post_identity_rmse_direct = 1.0000066644564635e-8
ridge = 1.0e-8
post_identity_rmse_pinv = 1.0000065713772241e-8
solver = "pinv"
cond_regularized = 1.0000000053404332
post_identity_rmse = 1.0000065713772241e-8

[outputs]
figure_raw = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/calibration_outputs/_full1/responses_5x4_three_methods_raw.png"
responses_csv = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/calibration_outputs/_full1/responses_5x4_all_methods.csv"
responses_hdf5 = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/calibration_outputs/_full1/responses_5x4_all_methods.hdf5"
figure_corrected = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/calibration_outputs/_full1/responses_5x4_three_methods_corrected.png"

[responses]
numerical_ensembles_used = 384
gfdt_samples_used = 150000
n_lags = 60
tmax_effective = 6.0

    [responses.finite_difference_h]
    c = 0.05
    b = 0.05
    h = 0.005
    F = 0.05

[checkpoint]
epoch = 20
path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/runs_J10/run_026/model/score_model_epoch_0020.bson"
