rmse_unet_vs_numerical = 245.2151516385775
global_kl = 0.001523750563886247
epoch = 120
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_013/model/checkpoints/epoch_0120.bson"
avg_mode_kl_clipped = 0.009530464506221713

[langevin_metrics]
avg_mode_js_clipped = 0.0023460816459687627
global_kl_from_run_langevin = 0.001523750563886247
avg_mode_kl_clipped = 0.009530464506221713
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.013793670343000703

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_013/figures/eval_epoch_0120/responses/run_001/responses_6x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_013/figures/eval_epoch_0120/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_013/figures/eval_epoch_0120/figD_responses_6x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_013/figures/eval_epoch_0120/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_013/figures/eval_epoch_0120/figC_dynamics_2x2.png"
