rmse_unet_vs_numerical = 161.0218707394555
global_kl = 0.0022014746785532537
epoch = 240
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/model/checkpoints/epoch_0240.bson"
avg_mode_kl_clipped = 0.007111844042173186

[langevin_metrics]
avg_mode_js_clipped = 0.0017736222645391227
global_kl_from_run_langevin = 0.0022014746785532537
avg_mode_kl_clipped = 0.007111844042173186
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.009196560213370581

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0240/responses/run_001/responses_6x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0240/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0240/figD_responses_6x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0240/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0240/figC_dynamics_2x2.png"
