rmse_unet_vs_numerical = 300.84017089858054
global_kl = 0.0016143149206878666
epoch = 180
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/model/checkpoints/epoch_0180.bson"
avg_mode_kl_clipped = 0.007297819497759943

[langevin_metrics]
avg_mode_js_clipped = 0.001805615386676342
global_kl_from_run_langevin = 0.0016143149206878666
avg_mode_kl_clipped = 0.007297819497759943
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.009314353498139562

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0180/responses/run_001/responses_6x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0180/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0180/figD_responses_6x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0180/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_017/figures/eval_epoch_0180/figC_dynamics_2x2.png"
