run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004"
updated_at = "2026-02-23T12:57:54"

[evaluation]
epochs = [60, 120, 180]
best_epoch = 120
rmse_unet_vs_numerical = [+inf, +inf, +inf]
best_avg_mode_kl_clipped = 0.005590710870067468
avg_mode_kl_clipped = [0.09900007190049302, 0.005590710870067468, 0.006574562543214874]
target_avg_mode_kl = 0.01
num_evaluations = 3
best_metrics_toml = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/metrics/epoch_0120_metrics.toml"

    [[evaluation.details]]
    fig_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0060"
    global_kl = 0.07792073637850035
    epoch = 60
    response_summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0060/responses/run_001/responses_6x5_summary.toml"
    avg_mode_kl_clipped = 0.09900007190049302
    figure_B = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0060/figB_stats_2x2.png"
    tag = "eval_epoch_0060"
    rmse_unet_vs_numerical = +inf
    figure_D = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0060/figD_responses_6x5.png"
    response_run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0060/responses/run_001"
    checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/model/checkpoints/epoch_0060.bson"
    figure_C = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0060/figC_dynamics_2x2.png"
    metrics_toml = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/metrics/epoch_0060_metrics.toml"
    [[evaluation.details]]
    fig_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120"
    global_kl = 0.0006472022810000002
    epoch = 120
    response_summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses/run_001/responses_6x5_summary.toml"
    avg_mode_kl_clipped = 0.005590710870067468
    figure_B = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/figB_stats_2x2.png"
    tag = "eval_epoch_0120"
    rmse_unet_vs_numerical = +inf
    figure_D = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/figD_responses_6x5.png"
    response_run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses/run_001"
    checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/model/checkpoints/epoch_0120.bson"
    figure_C = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/figC_dynamics_2x2.png"
    metrics_toml = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/metrics/epoch_0120_metrics.toml"
    [[evaluation.details]]
    fig_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0180"
    global_kl = 0.0002735099125899833
    epoch = 180
    response_summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0180/responses/run_001/responses_6x5_summary.toml"
    avg_mode_kl_clipped = 0.006574562543214874
    figure_B = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0180/figB_stats_2x2.png"
    tag = "eval_epoch_0180"
    rmse_unet_vs_numerical = +inf
    figure_D = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0180/figD_responses_6x5.png"
    response_run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0180/responses/run_001"
    checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/model/checkpoints/epoch_0180.bson"
    figure_C = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0180/figC_dynamics_2x2.png"
    metrics_toml = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/metrics/epoch_0180_metrics.toml"

[parameters_used]
langevin = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/params/parameters_langevin_used.toml"
responses = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/params/parameters_responses_used.toml"
train = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/params/parameters_train_used.toml"
pipeline = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/params/parameters_pipeline_used.toml"

[training]
epochs = 180
model_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/model/score_model.bson"
figure_A = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/training/figA_training_3panels.png"
training_metrics_csv = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/training/training_metrics.csv"
checkpoint_every = 60
state_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/model/training_state_latest.bson"
checkpoint_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/model/checkpoints"
