metrics_txt_path = ""
eval_config_path = ""
epoch = 40

[metrics]
kl_low_q = 0.001
avg_mode_kl_raw = 0.1267771714072313
score_pred_mse = 0.7356154875785288
avg_mode_l1_raw = 0.00594124984610345
avg_channel_std_abs_error = 0.5795692205429077
avg_mode_kl_clipped = 0.12325107020673773
avg_mode_l1_clipped = 0.005871917300090626
avg_x_channel_kl_raw = 0.19603935226298685
score_pred_corr = 0.5143488558963867
avg_channel_std_rel_error = 0.5582611150171378
avg_mode_js_clipped = 0.035564080871706906
max_mode_kl_raw = 0.27446826867291924
avg_y_channels_kl_raw = 0.11985095332165575
kl_high_q = 0.999
avg_x_channel_kl_clipped = 0.1917159682576655
global_kl_from_run_langevin = 0.11572516097779433
avg_mode_js_raw = 0.03674795050636553
avg_y_channels_kl_clipped = 0.11640458040164496
target_avg_mode_kl = 0.05
avg_channel_mean_abs_error = 0.10198800265789032
max_mode_kl_clipped = 0.2713408296033501
