figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_018/figures/eval_epoch_0060/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_018/figures/eval_epoch_0060/figC_dynamics_2x2.png"
observations_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/data/l96_arnold_datasets.hdf5"
device = "GPU:1"
metrics_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_018/metrics/epoch_0060_langevin_metrics.txt"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_018/model/checkpoints/epoch_0060.bson"

[metrics]
avg_mode_js_clipped = 0.0023924385571949397
global_kl_from_run_langevin = 0.0029576768702526683
avg_mode_kl_clipped = 0.009605719604619065
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.01550955864288039
