smape_gaussian_vs_numerical = 0.6569179110055261
global_kl = 0.0046635929065455585
epoch = 20
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_035/model/checkpoints/epoch_0020.bson"
avg_mode_kl_clipped = 0.007296987251654829
smape_unet_vs_numerical = 0.38501715730691244

[langevin_metrics]
avg_mode_js_clipped = 0.0018455650344239925
global_kl_from_run_langevin = 0.0046635929065455585
avg_mode_kl_clipped = 0.007296987251654829
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.01381153688560934
stein_sample_stride = 167.0

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_035/figures/eval_epoch_0020/responses/run_001/responses_5x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_035/figures/eval_epoch_0020/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_035/figures/eval_epoch_0020/figD_responses_5x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_035/figures/eval_epoch_0020/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_035/figures/eval_epoch_0020/figC_dynamics_2x2.png"
