figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_029/figures/eval_epoch_0020/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_029/figures/eval_epoch_0020/figC_dynamics_2x2.png"
observations_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/data/l96_arnold_datasets.hdf5"
device = "GPU:1"
metrics_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_029/metrics/epoch_0020_langevin_metrics.txt"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_029/model/checkpoints/epoch_0020.bson"

[metrics]
avg_mode_js_clipped = 0.0032982494273536347
global_kl_from_run_langevin = 0.008327858729903917
avg_mode_kl_clipped = 0.013274586131386204
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.022074810533344515
stein_sample_stride = 167.0
