cache_regenerated = true
output_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses_patched/run_001"
response_kind = "heaviside"
run_id = "run_001"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/model/checkpoints/epoch_0120.bson"
apply_score_correction = true
h_used = [0.05, 0.02, 0.01, 0.00125, 0.01]
cache_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/cache/responses/baseline_d4e98787404bf36d9034228bbd7fbab88248572b.hdf5"

[numerical_diag]
valid_fraction = [1.0, 1.0, 1.0, 1.0, 1.0]
valid_counts = [2048, 2048, 2048, 2048, 2048]
h_attempts = [1, 1, 1, 3, 1]

[figures]
raw = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses_patched/run_001/responses_6x5_selected_methods_raw.png"
main = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses_patched/run_001/responses_6x5_selected_methods.png"
corrected = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses_patched/run_001/responses_6x5_selected_methods_corrected.png"

[outputs]
responses_csv = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses_patched/run_001/responses_6x5_selected_methods.csv"
responses_hdf5 = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses_patched/run_001/responses_6x5_selected_methods.hdf5"
parameters_used = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_004/figures/eval_epoch_0120/responses_patched/run_001/parameters_used.toml"

[rmse.numerics_vs_unet_corrected]
overall = 118177.56231060269

    [rmse.numerics_vs_unet_corrected.per_param]
    sigma = 124.4335103253952
    alpha2 = 16820.26012683287
    alpha1 = 1559.0951236085043
    alpha3 = 263712.5325737861
    alpha0 = 117.98247652578493

[rmse.numerics_vs_gaussian]
overall = 169567.85945411253

    [rmse.numerics_vs_gaussian.per_param]
    sigma = 116.00840832609269
    alpha2 = 26257.291562965318
    alpha1 = 2364.5599715681537
    alpha3 = 378247.54617366905
    alpha0 = 196.59810400243686

[rmse.numerics_vs_unet_raw]
overall = 113516.4430904963

    [rmse.numerics_vs_unet_raw.per_param]
    sigma = 129.69222049678623
    alpha2 = 16156.200566459234
    alpha1 = 1584.6125898828825
    alpha3 = 253310.74692057932
    alpha0 = 170.64657182326528

[closure_parameters_used]
sigma = 0.22408113973792695
alpha2 = 0.0004226502150517753
alpha1 = 1.116425972669803
alpha3 = -0.003108940311701304
beta_tail = -2.0
alpha0 = 0.7610633766768744
F = 20.0
