metrics_txt_path = ""
eval_config_path = ""
epoch = 50

[metrics]
kl_low_q = 0.001
avg_mode_kl_raw = 0.044198109003855034
score_pred_mse = 0.8361200063121708
avg_mode_l1_raw = 0.0035033307351760965
avg_channel_std_abs_error = 0.1713012307882309
avg_mode_kl_clipped = 0.040400332115441764
avg_mode_l1_clipped = 0.0034895104000552484
avg_x_channel_kl_raw = 0.04360481883641268
score_pred_corr = 0.40505641427928085
avg_channel_std_rel_error = 0.16451298699957723
avg_mode_js_clipped = 0.010680205366882268
max_mode_kl_raw = 0.11930942417058457
avg_y_channels_kl_raw = 0.04425743802059928
kl_high_q = 0.999
avg_x_channel_kl_clipped = 0.040072024274595046
global_kl_from_run_langevin = 0.022649028714255504
avg_mode_js_raw = 0.011161426130405099
avg_y_channels_kl_clipped = 0.04043316289952643
target_avg_mode_kl = 0.05
avg_channel_mean_abs_error = 0.03179134428501129
max_mode_kl_clipped = 0.11713032546637521
