metrics_txt_path = ""
eval_config_path = ""
epoch = 30

[metrics]
kl_low_q = 0.001
avg_mode_kl_raw = 0.046257366424726214
score_pred_mse = 0.8459800926881039
avg_mode_l1_raw = 0.0035009061197905826
avg_channel_std_abs_error = 0.20206932723522186
avg_mode_kl_clipped = 0.042532080453993065
avg_mode_l1_clipped = 0.0034784383625947202
avg_x_channel_kl_raw = 0.04162981091551169
score_pred_corr = 0.3927525154063701
avg_channel_std_rel_error = 0.19404892176594413
avg_mode_js_clipped = 0.01143480053811943
max_mode_kl_raw = 0.1356587154862832
avg_y_channels_kl_raw = 0.04672012197564765
kl_high_q = 0.999
avg_x_channel_kl_clipped = 0.037824588739378606
global_kl_from_run_langevin = 0.027790352439964413
avg_mode_js_raw = 0.012019682701511885
avg_y_channels_kl_clipped = 0.043002829625454514
target_avg_mode_kl = 0.05
avg_channel_mean_abs_error = 0.03700726851820946
max_mode_kl_clipped = 0.13397754517919094
