figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs/run_005/figures/eval_epoch_0090/figB_stats_4x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs/run_005/figures/eval_epoch_0090/figC_dynamics_2x2.png"
observations_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/data/dataset_c45390420f42ffabe38b95cf1dab85d2c77799c2.hdf5"
device = "GPU:1"
metrics_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs/run_005/metrics/epoch_0090_langevin_metrics.txt"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/runs/run_005/model/score_model.bson"

[metrics]
avg_mode_js_clipped = 0.004171164046586205
global_kl_from_run_langevin = 0.008209634875292391
avg_mode_kl_clipped = 0.01662380959943289
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.01984787317458181
stein_sample_stride = 34.0
