[paths]
datasets_hdf5 = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/optimization_campaigns/campaign_jacobian_8h_20260225/data/dataset_2f60b34b34f01a3808208f6e6f058233993570ff.hdf5"

[twoscale]
stochastic_x_noise = false
J = 32
c = 10.0
process_noise_sigma = 0.0
b = 10.0
dt = 0.005
K = 8
h = 1.0
F = 20.0

[closure]
alpha2_initial = -0.0136
fit_dataset_role = "two_scale_observed"
fit_samples = 50000
fit_min_samples = 500
alpha3_initial = 0.00235
fit_start_index = 2
alpha1_initial = 1.3
auto_fit = false
alpha0_initial = 0.341
sigma_initial = 0.467
F = 20.0

[datasets.gfdt_stochastic]
key = "x_gfdt_stochastic"
spinup_steps = 2000
save_every = 2
rng_seed = 777
nsamples = 150000

[datasets.train_stochastic]
key = "x_train_stochastic"
spinup_steps = 2000
save_every = 200
rng_seed = 11
nsamples = 300000
target_spacing = 1.0

[datasets.two_scale_observed]
key = "x_two_scale_observed"
spinup_steps = 2000
save_every = 200
rng_seed = 101
nsamples = 200000
