rmse_unet_vs_numerical = 307.1320492311313
global_kl = 0.008886138190302083
epoch = 120
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_021/model/checkpoints/epoch_0120.bson"
avg_mode_kl_clipped = 0.011819532736539295

[langevin_metrics]
avg_mode_js_clipped = 0.002907802103232963
global_kl_from_run_langevin = 0.008886138190302083
avg_mode_kl_clipped = 0.011819532736539295
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.023042936828904858

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_021/figures/eval_epoch_0120/responses/run_001/responses_6x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_021/figures/eval_epoch_0120/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_021/figures/eval_epoch_0120/figD_responses_6x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_021/figures/eval_epoch_0120/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_021/figures/eval_epoch_0120/figC_dynamics_2x2.png"
