cache_regenerated = false
output_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/figures/eval_epoch_0180/responses/run_001"
response_kind = "impulse"
run_id = "run_001"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/model/checkpoints/epoch_0180.bson"
apply_score_correction = true
h_used = [0.05, 0.02, 0.01, 0.0025, 0.01]
cache_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/cache/responses/baseline_621b382c7251a19b6b0c7fd818d195cc9fff4bd5.hdf5"

[numerical_diag]
valid_fraction = [1.0, 1.0, 1.0, 0.974609375, 1.0]
valid_counts = [2048, 2048, 2048, 1996, 2048]
h_attempts = [1, 1, 1, 2, 1]

[figures]
raw = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/figures/eval_epoch_0180/responses/run_001/responses_6x5_selected_methods_raw.png"
main = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/figures/eval_epoch_0180/responses/run_001/responses_6x5_selected_methods.png"
corrected = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/figures/eval_epoch_0180/responses/run_001/responses_6x5_selected_methods_corrected.png"

[outputs]
responses_csv = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/figures/eval_epoch_0180/responses/run_001/responses_6x5_selected_methods.csv"
responses_hdf5 = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/figures/eval_epoch_0180/responses/run_001/responses_6x5_selected_methods.hdf5"
parameters_used = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_007/figures/eval_epoch_0180/responses/run_001/parameters_used.toml"

[rmse.numerics_vs_unet_corrected]
overall = 1.1068888130360136e6

    [rmse.numerics_vs_unet_corrected.per_param]
    sigma = 1475.0037655419899
    alpha2 = 8780.350405296589
    alpha1 = 1555.5791791967667
    alpha3 = 2.475062117268126e6
    alpha0 = 218.56272644357213

[rmse.numerics_vs_gaussian]
overall = 1.110173045662386e6

    [rmse.numerics_vs_gaussian.per_param]
    sigma = 1432.773184960488
    alpha2 = 22842.673253540815
    alpha1 = 2492.5135847684733
    alpha3 = 2.482315618516198e6
    alpha0 = 271.0400359244045

[rmse.numerics_vs_unet_raw]
overall = 1.107446496389126e6

    [rmse.numerics_vs_unet_raw.per_param]
    sigma = 1448.2627136620017
    alpha2 = 14360.950841535634
    alpha1 = 1825.9539801367782
    alpha3 = 2.47628289609802e6
    alpha0 = 248.6629448074961

[closure_parameters_used]
sigma = 0.467
alpha2 = -0.0136
alpha1 = 1.3
alpha3 = -0.00235
beta_tail = -2.0
alpha0 = 0.341
F = 20.0
