rmse_unet_vs_numerical = 451.77177457323074
global_kl = 0.06691600694132767
epoch = 60
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_014/model/checkpoints/epoch_0060.bson"
avg_mode_kl_clipped = 0.08500643600363825

[langevin_metrics]
avg_mode_js_clipped = 0.017771796967293522
global_kl_from_run_langevin = 0.06691600694132767
avg_mode_kl_clipped = 0.08500643600363825
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.10046414387959124

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_014/figures/eval_epoch_0060/responses/run_001/responses_6x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_014/figures/eval_epoch_0060/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_014/figures/eval_epoch_0060/figD_responses_6x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_014/figures/eval_epoch_0060/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_014/figures/eval_epoch_0060/figC_dynamics_2x2.png"
