rmse_unet_vs_numerical = 277090.6848729313
global_kl = 0.1196789577296175
epoch = 2
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/model/checkpoints/epoch_0002.bson"
avg_mode_kl_clipped = 0.7515997960626137

[langevin_metrics]
avg_mode_js_clipped = 0.2233573851349891
global_kl_from_run_langevin = 0.1196789577296175
avg_mode_kl_clipped = 0.7515997960626137
langevin_ensembles = 32.0
target_avg_mode_kl = 0.05
langevin_resolution = 8.0
langevin_nsteps = 2500.0
max_mode_kl_clipped = 0.9696162471123954

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0002/responses/run_001/responses_6x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0002/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0002/figD_responses_6x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0002/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0002/figC_dynamics_2x2.png"
