rmse_unet_vs_numerical = 274603.18132677913
global_kl = 0.11484185735073787
epoch = 1
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/model/checkpoints/epoch_0001.bson"
avg_mode_kl_clipped = 0.7748661819144719

[langevin_metrics]
avg_mode_js_clipped = 0.2284109957395237
global_kl_from_run_langevin = 0.11484185735073787
avg_mode_kl_clipped = 0.7748661819144719
langevin_ensembles = 32.0
target_avg_mode_kl = 0.05
langevin_resolution = 8.0
langevin_nsteps = 2500.0
max_mode_kl_clipped = 1.0032994435097313

[responses]
summary = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0001/responses/run_001/responses_6x5_summary.toml"
run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0001/responses/run_001"

[figures]
figD = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0001/figD_responses_6x5.png"
figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0001/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/_smoke/runs/run_005/figures/eval_epoch_0001/figC_dynamics_2x2.png"
