run_dir = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/runs_J2/run_005"
parameters_used_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/runs_J2/run_005/parameters_used.toml"
updated_at = "2026-02-15T18:44:46"

[evaluation]
num_langevin_evaluations = 1
epochs = [1]
best_epoch = 1
global_kl = [0.11805553845048367]
best_avg_mode_kl_clipped = 19.34795586243422
avg_mode_kl_clipped = [19.34795586243422]
best_metrics_toml = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/runs_J2/run_005/metrics/epoch_0001_metrics.toml"

[raw_parameters.run]
J = 2
run_folder_prefix = "runs_J"
seed = 7
run_id_padding = 3
runs_root = "scripts/L96"

[raw_parameters.langevin]
resolution = 10
burn_in = 20
device = "GPU:0"
pdf_bins = 60
boundary_min = -8.0
nsteps = 200
boundary_max = 8.0
dt = 0.0025
ensembles = 2
use_boundary = true

[raw_parameters.output]
save_per_epoch_eval = true
save_checkpoints = true
checkpoint_every = 10

[raw_parameters.data]
dataset_filename = "l96_timeseries.hdf5"
integration_params_filename = "integration_params.toml"
normalization_mode = "split_xy"
dataset_key = "timeseries"
generate_if_missing = true
path = "scripts/L96/observations/J10/l96_timeseries.hdf5"
observations_root = "scripts/L96/observations"

    [raw_parameters.data.generation]
    c = 10.0
    nsamples = 12000
    b = 10.0
    dt = 0.005
    h = 1.0
    spinup_steps = 20000
    process_noise_sigma = 0.03
    rng_seed = 7
    save_every = 10
    K = 36
    F = 10.0

[raw_parameters.train]
num_training_epochs = 1
sigma = 0.06
lr = 0.0008
channel_multipliers = [1, 2]
device = "GPU:0"
progress = false
batch_size = 128
base_channels = 16

    [raw_parameters.train.kl_eval]
    kl_eval_interval_epochs = 1
    enabled = true

[raw_parameters.figures]
dpi = 110
style = "publication"

[training]
model_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/runs_J2/run_005/model/score_model.bson"
figure_A = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/L96/runs_J2/run_005/figures/training/figA_training_2x1.png"
