figB = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_016/figures/eval_epoch_0060/figB_stats_2x2.png"
figC = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_016/figures/eval_epoch_0060/figC_dynamics_2x2.png"
observations_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/data/l96_arnold_datasets.hdf5"
device = "GPU:1"
metrics_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_016/metrics/epoch_0060_langevin_metrics.txt"
checkpoint_path = "/home/ludogio/Documents/JuliaProjects/ScoreUNet1D.jl/scripts/arnold/runs/run_016/model/checkpoints/epoch_0060.bson"

[metrics]
avg_mode_js_clipped = 0.002972221269096688
global_kl_from_run_langevin = 0.002175515730702381
avg_mode_kl_clipped = 0.012116573952737436
langevin_ensembles = 64.0
target_avg_mode_kl = 0.01
langevin_resolution = 20.0
langevin_nsteps = 12000.0
max_mode_kl_clipped = 0.019407074838767958
